networks:
  millau:
    external: true
services:
  proxy:
    image: codelev/millau:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - millau