services:
  proxy:
    image: codelev/millau:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:80"
  echo:
    image: codelev/echo-spring
    labels:
      - "millau.enabled=true"
      - "millau.port=9000"
    ports:
      - "9000"
